Home page updates
Volta-Audio/volta-audio.github.io pull request #11
Opened 2021-05-05 20:08 UTC by declanslevin

Changes:

- [ ] Update copy for ArtistsRequestAccess component, add sync section and icons
- [ ] Add RecentArtists carousel component section
- [ ] Add JoinWaitlist component section
- [ ] Add Endorsement carousel component section
- [ ] Add Discord community component section
- [ ] Update NewsletterSignup component copy
- [ ] Some small design tweaks

The home page should match the designs in both desktop and mobile view.

2021-05-07 07:18 UTC, abinocoe requested changes

2021-05-07 07:18 UTC, abinocoe commented on src/components/footer.tsx
> +  background-color: #232323;
if this is what the 'black' is supposed to be, think about swapping the value out in the theme

2021-05-07 07:18 UTC, abinocoe commented on src/containers/EndorsementCarousel.tsx
> +const EndorsementCarousel = () => {
Is this a carousel? I'd probably rename it

2021-05-07 07:18 UTC, abinocoe commented on src/containers/JoinWaitlist.tsx
> +  padding: 194px 0 234px;
these numbers look kinda wild - have a word with Arthur, just double check the default spacings for this module, most of them have a repeated value which is used at the top and bottom.

2021-05-07 07:18 UTC, abinocoe commented on src/containers/RecentArtists.tsx
> +  padding-top: ${({ theme: { spacing } }) => spacing.l};
is `spacing.l` a thing? I thought it was large 🤷🏻‍♀️

2021-05-07 07:18 UTC, abinocoe commented on src/containers/RecentArtists.tsx
> +      </ScrollContainer>
as there's a lot of copy/paste here from the carousel example on the moda page, I would create a carousel component which you perhaps just pass an array of objects to, containing the config for each element, e.g. something like `[{src: "", alt: "", name: ""},{src: "", alt: "", name: ""},...]` etc so it can be reused more easily. Will read much cleaner too when you're importing it.

2021-05-07 07:18 UTC, abinocoe commented on src/containers/Vision.tsx
> +    margin-right: -152px;
be careful with this, make sure that it displays reasonably on a range of phone sizes (obvs lol) and consider using a percentage if it's not working

2021-05-07 17:44 UTC, declanslevin commented on src/containers/RecentArtists.tsx
> +  padding-top: ${({ theme: { spacing } }) => spacing.l};
I tried `spacing.large` but it doesn't apply the padding 🤔 🤷‍♂️

2021-05-10 08:19 UTC, abinocoe commented on src/containers/RecentArtists.tsx
> +  padding-top: ${({ theme: { spacing } }) => spacing.l};
👍🏻 my mistake. these are defined in the theme folder where the styled components default theme is set up, so you can check what you can use there

2021-05-11 15:05 UTC, merged